# frozen_string_literal: true
source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

ruby '>=2.3.4'

# Added at 2017-08-23 17:19:22 +0300 by maxim:
gem "nordea-filetransfer", "~> 0.2.1"


# Added at 2017-08-23 19:50:27 +0300 by maxim:
gem "activesupport", "~> 5.1"
# Added at 2017-08-29 15:51:35 +0300 by maxim:
gem "rjr", "~> 0.19.3"

# replaced with local version
# Added at 2017-09-11 23:51:21 +0300 by maxim:
#gem "jimson", "~> 0.9.1"

# Added at 2017-09-13 12:21:57 +0300 by maxim:
gem "dotenv", "~> 2.2"

# Added at 2017-10-10 16:26:05 +0300 by maxim:
gem "oj", "~> 3.3"



# Added at 2017-10-10 17:23:17 +0300 by maxim:
#gem "multi_json", "~> 1.12"

# Added at 2017-10-10 17:34:23 +0300 by maxim:
gem "jimson", "~> 0.10.0"

# Added at 2017-10-10 18:05:41 +0300 by maxim:
# gem "yajl", "~> 0.3.4"